Marriage_Moments/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

import authentication_module.views
import photographer.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', authentication_module.views.login, name='login'),
    path('authentication/', include('authentication_module.urls', namespace='authentication_module')),
    path('customer/', include('customer.urls', namespace='customer')),
    path('photographer/', include('photographer.urls', namespace='photographer')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authentication_module/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

import authentication_module
from . import views

app_name = 'authentication_module'

urlpatterns = [
    path('signup_photographer/', views.register_photographer, name='signup_photographer'),
    path('signup_customer/', views.register_customer, name='signup_customer'),
    path('login/', views.login, name='login'),
    path('logout/',views.logout, name='logout'),

]

customer/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

import authentication_module
import customer.views
from . import views
import photographer.views
app_name = 'customer'

urlpatterns = [
    path('', views.home, name='home'),
    path('book-photographer/', customer.views.book_photographer, name='book-photographer'),

]

photographer/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

import authentication_module.views
import photographer.views

app_name = 'photographer'

urlpatterns = [
    path('', photographer.views.home, name='home'),
    path('details/<slug:id>/', photographer.views.photographer_details, name='photographer-details'),
    path('add-photo', photographer.views.add_portfolio_photo, name='add-photo'),
    path('add-package', photographer.views.add_photography_package, name='add-package'),
    path('delete-package', photographer.views.delete_package, name='delete-package'),
    path('update-bio', photographer.views.update_bio, name='update-bio'),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

customer/models.py
from django.db import models

# Create your models here.

photographer/models.py
from django.db import models


# Create your models here.


class UserType(models.Model):
    type = models.CharField(max_length=20)

    def __str__(self):
        return self.type

class User(models.Model):
    user_type = models.ForeignKey(UserType, on_delete=models.CASCADE)
    username = models.CharField(max_length=20)
    password = models.CharField(max_length=30)
    actual_id = models.IntegerField()

    def __str__(self):
        return self.username

class Photographer(models.Model):
    name = models.CharField(max_length=30)
    phone = models.CharField(max_length=20)
    email = models.EmailField()
    age = models.IntegerField()
    address = models.CharField(max_length=200, null=True)
    sex = models.CharField(max_length=10)
    bio = models.CharField(max_length=300)
    photo = models.ImageField(null=True)

    def __str__(self):
        return self.name + " | " + self.phone

class Customer(models.Model):
    name = models.CharField(max_length=30)
    email = models.EmailField()
    phone = models.CharField(max_length=20, null=True)
    age = models.IntegerField()
    address = models.CharField(max_length=200, null=True)
    sex = models.CharField(max_length=10)

    def __str__(self):
        return self.name

class Portfolio(models.Model):
    photographer = models.ForeignKey(Photographer, on_delete=models.CASCADE)
    caption = models.CharField(max_length=50)
    photo = models.ImageField()


class Photography_Package(models.Model):
    photographer = models.ForeignKey(Photographer, on_delete=models.CASCADE)
    name = models.CharField(max_length=30)
    description = models.CharField(max_length=400)
    fee = models.IntegerField()

    def __str__(self):
        return str(self.photographer) + " | " + self.name

class Order(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    package = models.ForeignKey(Photography_Package, on_delete=models.CASCADE, null=True)
    date = models.DateField()

customer/views.py
from datetime import datetime

from django.shortcuts import render, redirect, reverse

from photographer.models import *


def home(request):
    if 'phone' not in request.session:
        return redirect(reverse('authentication_module:login'))
    else:
        customer = Customer.objects.get(id=1)

        photographers = Photographer.objects.all()

        context = {
            'photographers': photographers
        }

        return render(request, 'customer/home.html', context)


def book_photographer(request):
    print(f"book photographer confirmed {id}")

    if request.method == 'POST':
        package_id = request.POST['package_id']

        customer = Customer.objects.get(phone=request.session['phone'])
        photography_package = Photography_Package.objects.get(id=package_id)

        order = Order(customer=customer, package=photography_package, date=datetime.today())
        order.save()

    return redirect(reverse('customer:home'))

templates/customer/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>Marriage Moments - Home</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico"/>
    <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet"/>
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'customer/css/styles.css' %}" rel="stylesheet"/>
</head>
<body>
{{ name }} {{ age }} {{ customer.phone }}
<!-- Navigation-->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid px-4 px-lg-5">
        <a class="navbar-brand" href="#!">Marriage Moments</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span
                class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                <li class="nav-item"><a class="nav-link active" aria-current="page" href="#!">Home</a></li>
                <li class="nav-item"><a class="nav-link" href="#!">About</a></li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">Shop</a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="#!">All Products</a></li>
                        <li>
                            <hr class="dropdown-divider"/>
                        </li>
                        <li><a class="dropdown-item" href="#!">Popular Items</a></li>
                        <li><a class="dropdown-item" href="#!">New Arrivals</a></li>
                    </ul>
                </li>
            </ul>

            <a class="btn btn-outline-dark mx-1" href="{% url 'authentication_module:logout' %}">
                <i class="bi bi-box-arrow-left"></i> Logout

            </a>


        </div>
    </div>
</nav>
<!-- Header-->
<header class="bg-dark py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="text-center text-white">
            <h1 class="display-4 fw-bolder">Capture Your Dreams!</h1>
            <p class="lead fw-normal text-white-50 mb-0">With Marriage Moments</p>
        </div>
    </div>
</header>


<div class="card text-bg-dark">
  <img src="{% static 'images/bg.jpg' %}" class="card-img" alt="...">
  <div class="card-img-overlay">
<section class="py-5">
    <div class="container px-4 px-lg-5 mt-5">
        <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
            {% for photographer in photographers %}

                <div class="col mb-5">
                    <div class="card h-100">
                        <!-- Product image-->
                        <img class="card-img-top" src="{{ photographer.photo.url }}" alt="..."/>
                        <!-- Product details-->
                        <div class="card-body p-4">
                            <div class="text-center">
                                <!-- Product name-->
                                <h5 class="fw-bolder">{{ photographer.name }}</h5>
                                <h5 class="fw-bolder">{{ photographer.bio }}</h5>
                                <h5 class="fw-bolder">{{ photographer.portfolio_set.0.url }}</h5>

                                <!-- Product price-->
                            </div>
                        </div>
                        <!-- Product actions-->
                        <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                            <div class="text-center"><a class="btn btn-outline-dark mt-auto"
                                                        href="{% url 'photographer:photographer-details' photographer.id %}">Show
                                Details</a>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</section>

  </div>
</div>


<!-- Section-->

<!-- Footer-->
<footer class="py-5 bg-dark bottom">
    <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Marriage Moments 2022</p></div>
</footer>
<!-- Bootstrap core JS-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
<!-- Core theme JS-->
<script src="{% static 'customer/js/scripts.js' %}"></script>
</body>
</html>