Marriage_Moments/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

import authentication_module.views
import photographer.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', authentication_module.views.login, name='login'),
    path('authentication/', include('authentication_module.urls', namespace='authentication_module')),
    path('customer/', include('customer.urls', namespace='customer')),
    path('photographer/', include('photographer.urls', namespace='photographer')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authentication_module/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

import authentication_module
from . import views

app_name = 'authentication_module'

urlpatterns = [
    path('signup_photographer/', views.register_photographer, name='signup_photographer'),
    path('signup_customer/', views.register_customer, name='signup_customer'),
    path('login/', views.login, name='login'),
    path('logout/',views.logout, name='logout'),

]

customer/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

import authentication_module
import customer.views
from . import views
import photographer.views
app_name = 'customer'

urlpatterns = [
    path('', views.home, name='home'),
    path('book-photographer/', customer.views.book_photographer, name='book-photographer'),

]

photographer/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

import authentication_module.views
import photographer.views

app_name = 'photographer'

urlpatterns = [
    path('', photographer.views.home, name='home'),
    path('details/<slug:id>/', photographer.views.photographer_details, name='photographer-details'),
    path('add-photo', photographer.views.add_portfolio_photo, name='add-photo'),
    path('add-package', photographer.views.add_photography_package, name='add-package'),
    path('delete-package', photographer.views.delete_package, name='delete-package'),
    path('update-bio', photographer.views.update_bio, name='update-bio'),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

photographer/models.py
from django.db import models


# Create your models here.


class UserType(models.Model):
    type = models.CharField(max_length=20)

    def __str__(self):
        return self.type

class User(models.Model):
    user_type = models.ForeignKey(UserType, on_delete=models.CASCADE)
    username = models.CharField(max_length=20)
    password = models.CharField(max_length=30)
    actual_id = models.IntegerField()

    def __str__(self):
        return self.username

class Photographer(models.Model):
    name = models.CharField(max_length=30)
    phone = models.CharField(max_length=20)
    email = models.EmailField()
    age = models.IntegerField()
    address = models.CharField(max_length=200, null=True)
    sex = models.CharField(max_length=10)
    bio = models.CharField(max_length=300)
    photo = models.ImageField(null=True)

    def __str__(self):
        return self.name + " | " + self.phone

class Customer(models.Model):
    name = models.CharField(max_length=30)
    email = models.EmailField()
    phone = models.CharField(max_length=20, null=True)
    age = models.IntegerField()
    address = models.CharField(max_length=200, null=True)
    sex = models.CharField(max_length=10)

    def __str__(self):
        return self.name

class Portfolio(models.Model):
    photographer = models.ForeignKey(Photographer, on_delete=models.CASCADE)
    caption = models.CharField(max_length=50)
    photo = models.ImageField()


class Photography_Package(models.Model):
    photographer = models.ForeignKey(Photographer, on_delete=models.CASCADE)
    name = models.CharField(max_length=30)
    description = models.CharField(max_length=400)
    fee = models.IntegerField()

    def __str__(self):
        return str(self.photographer) + " | " + self.name

class Order(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    package = models.ForeignKey(Photography_Package, on_delete=models.CASCADE, null=True)
    date = models.DateField()

photographer/views.py
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render, redirect, reverse
from .models import *


# Create your views here.

def home(request):
    if 'phone' not in request.session:
        return redirect(reverse('authentication_module:login'))
    else:
        photographer = Photographer.objects.get(phone=request.session['phone'])
        context = {
            'photographer': photographer,
            'orders': Order.objects.filter(package__photographer=photographer),
            'packages': Photography_Package.objects.filter(photographer=photographer),
        }
        return render(request, 'photographer/dashboard.html', context)


def photographer_details(request, id):
    if 'phone' not in request.session:
        return redirect(reverse('authentication_module:login'))
    else:
        print('this function called')
        print(id)

        photographer = Photographer.objects.get(id=id)

        print("------------")
        print(Photography_Package.objects.filter(photographer=photographer))

        context = {
            'photographer': photographer,
            'portfolio_photos': Portfolio.objects.filter(photographer=photographer),
            'packages': Photography_Package.objects.filter(photographer=photographer),
        }
        return render(request, 'photographer/photographer_details.html', context)


def add_portfolio_photo(request):
    if 'phone' not in request.session:
        return redirect(reverse('authentication_module:login'))
    else:
        photo = request.FILES['photo']
        caption = request.POST['caption']

        # fetch from session cookie
        photographer = Photographer.objects.get(phone=request.session['phone'])

        portfolio = Portfolio(photographer=photographer, caption=caption, photo=photo)
        portfolio.save()

        return redirect(reverse('photographer:home'))


def add_photography_package(request):
    if request.method == "POST":
        name = request.POST['package_name']
        desc = request.POST['package_desc']
        fee = request.POST['fee']

        photographer = Photographer.objects.get(phone=request.session['phone'])

        package = Photography_Package(photographer=photographer, name=name, fee=fee, description=desc)
        package.save()

        return redirect(reverse('photographer:home'))


def delete_package(request):
    if request.method == "POST":
        id = request.POST['package_id']

        package = Photography_Package.objects.get(id=id)
        package.delete()

        print('package deleted')

    return redirect(reverse('photographer:home'))


def update_bio(request):
    if request.method == 'POST':
        bio = request.POST['bio']

        photographer = Photographer.objects.get(phone=request.session['phone'])
        photographer.bio = bio

        photographer.save()


    return redirect(reverse('photographer:home'))

templates/photographer/add-photography-packages.html
<form class="row row-cols-lg-auto g-3 align-items-center mt-3" method="post" action="{% url 'photographer:add-package' %}">
    {% csrf_token %}
    <div class="row">
        <div class="col">
            <input type="text" class="form-control" name="package_name" placeholder="Package Name">
        </div>
        <div class="col">
            <input type="text" class="form-control" name="package_desc" placeholder="Description">
        </div>

        <div class="col">
            <input type="number" class="form-control" name="fee" placeholder="Fee">
        </div>


    </div>

    <button type="submit" class="btn btn-outline-success"> Add Package </button>
</form>

templates/photographer/add-portfolio-photo-form.html
{% load static %}

<form class="row row-cols-lg-auto g-3 align-items-center mt-3" method="post" action="{% url 'photographer:add-photo'%}" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="col-12">
        <label class="visually-hidden" for="inlineFormInputGroupUsername">Caption</label>
        <div class="input-group">
            <input type="text" class="form-control" id="inlineFormInputGroupUsername" placeholder="Caption" name="caption">
        </div>
    </div>

    <div class="col-12">
        <label class="visually-hidden" for="inlineFormInputGroupUsername">Add Photo</label>
        <div class="input-group">

            <input type="file" class="form-control" id="inlineFormInputGroupUsername" placeholder="..." name="photo">
        </div>
    </div>


    <div class="col-12">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</form>

templates/photographer/dashboard.html
<!DOCTYPE html>
<html lang="en">

{% load static %}

<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>Welcome {{ photographer.name }}</title>
    <link href="https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css" rel="stylesheet"/>
    <!-- <link href="css/styles.css" rel="stylesheet"/> -->


    <link href="{% static 'photographer/css/dashboard.css' %}" rel="stylesheet"/>


    <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
</head>

<body class="sb-nav-fixed">
<nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
    <!-- Navbar Brand-->
    <a class="navbar-brand ps-3" href="index.html">Dashboard</a>
    <!-- Sidebar Toggle-->
    <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i
            class="fas fa-bars"></i></button>
    <!-- Navbar Search-->
    <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
        <div class="input-group">
            <input class="form-control" type="text" placeholder="Search for..." aria-label="Search for..."
                   aria-describedby="btnNavbarSearch"/>
            <button class="btn btn-primary" id="btnNavbarSearch" type="button"><i class="fas fa-search"></i></button>
        </div>
    </form>
    <!-- Navbar-->
    <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown"
               aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">

                <li><a class="dropdown-item" href="{% url 'authentication_module:logout' %}">Logout</a></li>
            </ul>
        </li>
    </ul>
</nav>
<div id="layoutSidenav">
    <div id="layoutSidenav_nav">
        <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
            <div class="sb-sidenav-menu">
                <div class="nav">
                    <div class="sb-sidenav-menu-heading">Core</div>
{#                    <a class="nav-link" href="index.html">#}
{#                        <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>#}
{#                    </a>#}

                </div>
            </div>
            <div class="sb-sidenav-footer">
                <div class="small">Logged in as:</div>
                {{ photographer.name }}
            </div>
        </nav>
    </div>
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid px-4">


                {% include 'photographer/add-portfolio-photo-form.html' %}

                {% include 'photographer/add-photography-packages.html' %}

                {% include 'photographer/update-bio.html' %}

                {% include 'photographer/order-table.html' %}

                {% include 'photographer/package-table.html' %}

            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid px-4">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; Your Website 2022</div>
                    <div>
                        <a href="#">Privacy Policy</a> &middot;
                        <a href="#">Terms &amp; Conditions</a>
                    </div>
                </div>
            </div>
        </footer>
    </div>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        crossorigin="anonymous"></script>
<script src="{% static 'photographer/js/scripts.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
<script src="assets/demo/chart-area-demo.js"></script>
<script src="assets/demo/chart-bar-demo.js"></script>
<script src="https://cdn.jsdelivr.net/npm/simple-datatables@latest" crossorigin="anonymous"></script>
<script src="js/datatables-simple-demo.js"></script>
</body>

</html>

templates/photographer/dashboard_summary_card.html
<div class="row mt-4">
    <div class="col-xl-3 col-md-6">
        <div class="card bg-primary text-white mb-4">
            <div class="card-body">Primary Card</div>
            <div class="card-footer d-flex align-items-center justify-content-between">
                <a class="small text-white stretched-link" href="#">View Details</a>
                <div class="small text-white"><i class="fas fa-angle-right"></i></div>
            </div>
        </div>
    </div>
    <div class="col-xl-3 col-md-6">
        <div class="card bg-warning text-white mb-4">
            <div class="card-body">Warning Card</div>
            <div class="card-footer d-flex align-items-center justify-content-between">
                <a class="small text-white stretched-link" href="#">View Details</a>
                <div class="small text-white"><i class="fas fa-angle-right"></i></div>
            </div>
        </div>
    </div>
    <div class="col-xl-3 col-md-6">
        <div class="card bg-success text-white mb-4">
            <div class="card-body">Success Card</div>
            <div class="card-footer d-flex align-items-center justify-content-between">
                <a class="small text-white stretched-link" href="#">View Details</a>
                <div class="small text-white"><i class="fas fa-angle-right"></i></div>
            </div>
        </div>
    </div>
    <div class="col-xl-3 col-md-6">
        <div class="card bg-danger text-white mb-4">
            <div class="card-body">Danger Card</div>
            <div class="card-footer d-flex align-items-center justify-content-between">
                <a class="small text-white stretched-link" href="#">View Details</a>
                <div class="small text-white"><i class="fas fa-angle-right"></i></div>
            </div>
        </div>
    </div>


</div>

templates/photographer/order-table.html
<table class="table table-striped table-hover">
    <thead>
    <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Date</th>
        <th scope="col">Phone</th>
        <th scope="col">Package</th>

    </tr>
    </thead>
    <tbody>

    {% for order in orders %}
        <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ order.customer.name }}</td>
            <td>{{ order.date }}</td>
            <td>{{ order.customer.phone }}</td>
            <td>{{ order.package.name }}</td>

        </tr>
    {% endfor %}


    </tbody>
</table>

templates/photographer/package-table.html
<table class="table table-striped table-hover">
    <thead>
    <tr>
        <th scope="col" class="text-center">#</th>
        <th scope="col" class="text-center">Name</th>
        <th scope="col" class="text-center">Description</th>
        <th scope="col" class="text-center">Fee</th>
        <th scope="col" class="text-center">Action</th>

    </tr>
    </thead>
    <tbody>

    {% for package in packages %}
        <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td class="text-center">{{ package.name }}</td>
            <td class="text-center">{{ package.description }}</td>
            <td class="text-center">{{ package.fee }}</td>
            <td class="text-center">
                <form action="{% url 'photographer:delete-package' %}" method="POST">
                    {% csrf_token %}
                    <input type="text" value="{{ package.id }}" name="package_id">
                    <button class="btn btn-outline-danger" type="submit">Delete</button>
                </form>
            </td>

        </tr>
    {% endfor %}


    </tbody>
</table>

templates/photographer/photographer_details.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>Marriage Moments - photographer details</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico"/>
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'photographer_details/css/styles.css' %}" rel="stylesheet"/>
</head>
<body>
<!-- Responsive navbar-->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="{% url 'customer:home' %}">Marriage Moments</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span
                class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-item"><a class="nav-link" href="#">Home</a></li>
                <li class="nav-item"><a class="nav-link" href="#!">About</a></li>
                <li class="nav-item"><a class="nav-link" href="#!">Contact</a></li>
                <li class="nav-item"><a class="nav-link active" aria-current="page" href="#">Blog</a></li>
            </ul>
        </div>
    </div>
</nav>
<!-- Page content-->

<div class="card text-bg-dark">
    <img src="{% static 'images/bg.jpg' %}" class="card-img" alt="...">
    <div class="card-img-overlay">
        <div class="container mt-5">
        <div class="row">
            <div class="col-lg-8">
                <!-- Post content-->
                <article>
                    <!-- Post header-->
                    <header class="mb-4">
                        <!-- Post title-->
                        <h1 class="fw-bolder mb-1">{{ photographer.name }}</h1>
                        <!-- Post meta content-->
                        <div class="text-muted fst-italic mb-2">Posted on January 1, 2022</div>
                        <!-- Post categories-->
                        <a class="badge bg-secondary text-decoration-none link-light" href="#!">Wedding</a>
                        <a class="badge bg-secondary text-decoration-none link-light" href="#!">Portraits</a>
                    </header>
                    <!-- Preview image figure-->
                    {#                <figure class="mb-4"><img class="img-fluid rounded"#}
                    {#                                          src="https://dummyimage.com/900x400/ced4da/6c757d.jpg" alt="..."/></figure>#}


                    <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="true">
                        <div class="carousel-inner">

                            {% for portfolio_photo in portfolio_photos %}
                                {% if forloop.counter == 1 %}
                                    <div class="carousel-item active">
                                        <img src="{{ portfolio_photo.photo.url }}" class="d-block w-100"
                                             alt="...">
                                    </div>
                                {% else %}
                                    <div class="carousel-item">
                                        <img src="{{ portfolio_photo.photo.url }}" class="d-block w-100"
                                             alt="...">
                                    </div>
                                {% endif %}
                            {% endfor %}

                        </div>
                        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators"
                                data-bs-slide="prev">
                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                            <span class="visually-hidden">Previous</span>
                        </button>
                        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators"
                                data-bs-slide="next">
                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                            <span class="visually-hidden">Next</span>
                        </button>
                    </div>

                    <!-- Post content-->
                    <section class="mb-5">
                        <div class="text-center mt-5">
                            <p class="fs-5 mb-4"><strong>{{ photographer.name }}</strong> is a photographer based
                                on {{ photographer.address }}</p>
                        </div>


                    </section>
                </article>
            </div>
            <!-- Side widgets-->
            <div class="col-lg-4">
                <!-- Search widget-->
                <div class="card mb-4">
                    <div class="card-header"><strong>Contact</strong></div>
                    <div class="card-body">
                        <div class="input-group">
                            <form action="{% url 'customer:book-photographer' %}" method="post">
                                {% csrf_token %}
                                <select class="form-select " aria-label="Default select example" name="package_id">
                                    <option selected>Open this select menu</option>
                                    {% for package in packages %}
                                        <option value="{{ package.id }}">{{ package.name }}</option>
                                    {% endfor %}>

                                </select>

                                <button type="submit" class="btn btn-primary" href="">Book Now</button>


                            </form>

                        </div>
                    </div>
                </div>
                <div class="card mb-4">
                    <div class="card-header"><strong>Packages we offer</strong></div>
                    <div class="card-body">

                        {% for package in packages %}
                            <p><strong>{{ package.name }} : </strong> {{ package.description }} {{ package.fee }}</p>
                        {% endfor %}


                    </div>
                </div>

            </div>


        </div>
    </div>

    </div>
</div>
    <!-- Footer-->
    <footer class="py-5 bg-dark ">
        <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Marriage Moments 2022</p></div>
    </footer>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="{% static 'photographer_details/js/scripts.js' %}"></script>
</body>
</html>

templates/photographer/update-bio.html
{% load static %}

<form action="{% url 'photographer:update-bio' %}" method="POST">
    {% csrf_token %}
    <div class="row">
        <div class="col-3">
            <input type="text" class="form-control" name="bio">

        </div>
        <div class="col-3">
            <button type="submit" class="btn btn-outline-primary">Update Bio</button>
        </div>

    </div>

</form>