Marriage_Moments/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

import authentication_module.views
import photographer.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', authentication_module.views.login, name='login'),
    path('authentication/', include('authentication_module.urls', namespace='authentication_module')),
    path('customer/', include('customer.urls', namespace='customer')),
    path('photographer/', include('photographer.urls', namespace='photographer')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authentication_module/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

import authentication_module
from . import views

app_name = 'authentication_module'

urlpatterns = [
    path('signup_photographer/', views.register_photographer, name='signup_photographer'),
    path('signup_customer/', views.register_customer, name='signup_customer'),
    path('login/', views.login, name='login'),
    path('logout/',views.logout, name='logout'),

]

customer/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

import authentication_module
import customer.views
from . import views
import photographer.views
app_name = 'customer'

urlpatterns = [
    path('', views.home, name='home'),
    path('book-photographer/', customer.views.book_photographer, name='book-photographer'),

]

templates/authentication/customer_signup.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
</head>
</head>
<body>



<div class="card text-bg-dark">
    <img src="{% static 'images/login.jpg' %}" style="height: 1080px;width: 1920px;" class="card-img" alt="...">
    <div class="card-img-overlay">
<div class="container">
    <div class="text-center mt-5 text-black">
                <h1>
                    Sign up
                </h1>
            </div>

    <form class="row g-3" method="post" action="{% url 'authentication_module:signup_customer' %}">
    {% csrf_token %}
    <div class="col-12">
        <label for="inputEmail4" class="text-black form-label">Name</label>
        <input type="text" class="form-control" id="inputEmail4" name="name">
    </div>

    <div class="col-12">
        <label for="inputAddress" class="text-black form-label">Email</label>
        <input type="email" class="form-control" id="inputAddress" placeholder="enter email" name="email">
    </div>


    <div class="col-6">
        <label for="inputAddress2" class="text-black form-label">Password</label>
        <input type="password" class="form-control" id="inputAddress2" placeholder="enter password" name="password1">
    </div>
    <div class="col-6">
        <label for="inputAddress2" class="text-black form-label">Confirm Password</label>
        <input type="password" class="form-control" id="inputAddress2" placeholder="enter password" name="password2">
    </div>

    <div class="col-md-6">
        <label for="inputAddress" class="text-black form-label">Address</label>
        <input type="text" class="form-control" id="inputAddress" placeholder="enter address" name="address">
    </div>
    <div class="col-md-6">
        <label for="inputCity" class="text-black form-label">Age</label>
        <input type="text" class="form-control" id="inputCity" name="age">
    </div>
    <div class="col-md-6">
        <label for="inputCity" class="text-black form-label">Sex</label>
        <input type="text" class="form-control" id="inputCity" name="sex">
    </div>
    <div class="col-md-6">
        <label for="inputCity" class="text-black form-label">Phone</label>
        <input type="text" class="form-control" id="inputCity" name="phone">
    </div>


    <div class="col-12">
        <button type="submit" class="btn btn-primary" style="width: 100%;">Sign Up</button>
    </div>
</form>

    <div class="text-center text-black mt-3">
        Already have an account? <a href="{% url 'authentication_module:login' %}"> Login</a>
    </div>

</div>


    </div>
</div>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8"
        crossorigin="anonymous"></script>
</body>
</html>

templates/authentication/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>

    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
</head>
<body>

<div class="card text-bg-dark">
    <img src="{% static 'images/login.jpg' %}" style="height: 1080px;width: 1920px;" class="card-img" alt="...">
    <div class="card-img-overlay">

        <div class="container">



            <h1 style="text-align: center" class="text-decoration-underline text-black">Welcome to Marriage Moments</h1>


            <form method="POST" action="{% url 'authentication_module:login' %}">
                {% csrf_token %}
                <div class="row my-5">
                    <label for="inputEmail3" class="text-black col-sm-2 col-form-label">Phone</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="inputEmail3" name="username">
                    </div>
                </div>
                <div class="row mb-3">
                    <label for="inputPassword3" class="text-black col-sm-2 col-form-label">Password</label>
                    <div class="col-sm-10">
                        <input type="password" class="form-control" id="inputPassword3" name="password">
                    </div>
                </div>
                <div class="text-center">
                    <button type="submit" class="btn btn-primary">Sign in</button>
                </div>
            </form>
            <div class="text-center">
                <p class="text-black">Sign up as <a
                        href="{% url 'authentication_module:signup_customer' %}">Customer</a></p>
                <p class="text-black">Sign up as <a href="{% url 'authentication_module:signup_photographer' %}">Photographer</a>
                </p>
            </div>
        </div>

    </div>
</div>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8"
        crossorigin="anonymous"></script>
</body>
</html>

templates/authentication/photographer_signup.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">

</head>
<body>

<div class="card text-bg-dark">
    <img src="{% static 'images/login.jpg' %}" style="height: 1080px;width: 1920px;" class="card-img" alt="...">
    <div class="card-img-overlay">
        <div class="container">
            <div class="text-center mt-5 text-black">
                <h1>
                    Sign up
                </h1>
            </div>

            <form class="row g-3 my-5" method="post" action="{% url 'authentication_module:signup_photographer' %}"
                  enctype="multipart/form-data">
                {% csrf_token %}
                <div class="col-12">
                    <label for="inputEmail4" class="text-black form-label">Name</label>
                    <input type="text" class="form-control" id="inputEmail4" name="name">
                </div>

                <div class="col-12">
                    <label for="inputAddress" class="text-black form-label">Email</label>
                    <input type="email" class="form-control" id="inputAddress" placeholder="enter email" name="email">
                </div>

                <div class="col-6">
                    <label for="inputAddress" class="text-black form-label">phone</label>
                    <input type="text" class="form-control" id="inputAddress" placeholder="enter phone no."
                           name="phone">
                </div>
                <div class="col-md-6">
                    <label for="inputCity" class="text-black form-label">Sex</label>
                    <input type="text" class="form-control" id="inputCity" name="sex">
                </div>
                <div class="col-6">
                    <label for="inputAddress2" class="text-black form-label">Password</label>
                    <input type="password" class="form-control" id="inputAddress2" placeholder="enter password"
                           name="password1">
                </div>
                <div class="col-6">
                    <label for="inputAddress2" class="text-black form-label">Confirm Password</label>
                    <input type="password" class="form-control" id="inputAddress2" placeholder="enter password"
                           name="password2">
                </div>
                <div class="col-md-6">
                    <label for="inputAddress" class="text-black form-label">Address</label>
                    <input type="text" class="form-control" id="inputAddress" placeholder="enter address"
                           name="address">
                </div>
                <div class="col-md-3">
                    <label for="inputCity" class="text-black form-label">Age</label>
                    <input type="text" class="form-control" id="inputCity" name="age">
                </div>
                <div class="col-md-3">
                    <label for="inputCity" class="text-black form-label">Add Image</label>
                    <input type="file" class="form-control" id="inputCity" name="image_select">
                    {#            <input class="form-control" type="file" name="image_select">#}
                </div>

                <div class="col-12">
                    <label for="inputCity" class="text-black form-label">Bio</label>
                    <input type="text" class="form-control" id="inputCity" name="bio">
                </div>
                <div class="text-center">
                    <button type="submit" class="btn btn-primary" style="width: 100%">Sign Up</button>
                </div>
            </form>
            <div class="text-center text-black">
                Already have an account? <a href="{% url 'authentication_module:login' %}"> Login</a>
            </div>
        </div>


    </div>
</div>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8"
        crossorigin="anonymous"></script>
</body>
</html>